export const CONSTANTS = {
    BASE_URL : 'https://5ed1ccb8.ngrok.io/',
    INTERNET_ISSUE : 'oops! You are not connected to the internet!',
    AUTH_FAIL : 'LoginId or password incorrect',
    SERVER_ERROR: 'Something went wrong',
    CART_EMPTY: 'Cart is empty',
    ORDER_STATUS_PROGRESS: 'in-progress',
    ORDER_STATUS_RECEIVED: 'recieved',
    ORDER_STATUS_CANCEL: 'cancel',
    PAGINATION_LIMIT: 20,
    CUSTOMER_CREATED: 'Customer created successfully',
    ADMIN_CREATED: 'Admin created successfully',
    PRODUCT_CREATED: 'Product added successfully',
    CATEGORY_CREATED: 'Category added successfully',
    ORDER_PLACED: 'Your order has been placed successfully',
    ORDER_IMPORTED: 'Order imported successfully',
}
