export const CONSTANTS = {
    BASE_URL : 'http://localhost:3000/',
    INTERNET_ISSUE : 'oops! You are not connected to the internet!',
    AUTH_FAIL : 'LoginId or password incorrect',
    SERVER_ERROR: 'Something went wrong',
    CART_EMPTY: 'Cart is empty',
    ORDER_STATUS_PROGRESS: 'in-progress',
    ORDER_STATUS_RECEIVED: 'recieved',
    ORDER_STATUS_CANCEL: 'cancel',
    PAGINATION_LIMIT: 20,
    CUSTOMER_CREATED: 'Customer created successfully',
    ADMIN_CREATED: 'Admin created successfully',
    PRODUCT_CREATED: 'Product added successfully',
    CATEGORY_CREATED: 'Category added successfully',
    ORDER_PLACED: 'Your order has been placed successfully',
    ORDER_IMPORTED: 'Order imported successfully',
    ORDER_CANCELLED: 'Order cancelled successfully',
    PASSWORD_MISMTACH: "Current Password and Re enter password don't match !",
    DEFUALT_PASSWORD: 'tradekings@123',
    INCORRECT_PASSWORD: 'Incorrect current password',
    PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
    PARENT_CATEGORY_NOT_FOUND: 'No parent category found! First add a parent category',
    CSV_DOWNLOADED: 'CSV Downloaded Successfully',
    CSV_DOWNLOAD_FAIL: 'Failed to download CSV'
}
